[project]
name = "llm-rag-bootcamp"
version = "0.0.1"
description = "Bootcamp on production LLMs and RAG by teaching you how to build an AI engine on top of your second brain, similar to Notion."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.3",
    "loguru>=0.7.3",
    "zenml[server]>=0.71.0",
]

[dependency-groups]
dev = ["pytest>=8.3.4", "ruff>=0.8.4"]

[tool.ruff]
target-version = "py312"

[project.scripts]
make_me_laugh = "second_brain:make_me_laugh"
